sudo: required
services:
  - docker

before_install:
  - docker build -t freshanthony/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true freshanthony/docker-react npm run test -- --coverage --watchAll=false
